# -*- coding: utf-8 -*-
"""Exercício-Cap3-Métodos-e-Funções.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15GIK2rh7YtCE_eJDABbXum9qPZnFhEU6
"""

# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

"""# Exercícios - Métodos e Funções"""

# Exercício 1 - Crie uma função que imprima a sequência de números pares entre 1 e 20 (a função não recebe parâmetro) e 
# depois faça uma chamada à função para listar os números      

def secPar():
    for i in range(2,21,2):
        print(i)

def secPar2(cont=0):
    if cont <= 21 and cont%2 == 0: 
        print(cont)
        
    if(cont<=21):
        return secPar2(cont+1)


secPar2()

def imprimir_pares():
    for x in range (0, 21):
        if x % 2 == 0 and x != 0:
            print(x)
    return "ok"

imprimir_pares()

