# -*- coding: utf-8 -*-
"""DSA-Python-Cap02-Exercicios

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1335BRDysmZzoqhKsiGLp8FEewRrb6AyZ
"""

# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

"""# Exercícios Cap02

"""

# Exercício 1 - Imprima na tela os números de 1 a 10. Use uma lista para armazenar os números.

'''
lista2 = range(1,11)
print(list(lista2))
'''
#or

'''
lista3 = []
for i in range(1,11):
    lista3.append(i)
    print(i, end=' ')
'''

#or

lista = []
def cont(i=1,f=11):
    if i != f:
        lista.append(i)
        return cont(i+1, f)
    else:
        return lista
cont()

# Exercício 2 - Crie uma lista de 5 objetos e imprima na tela
lista = ['banana','maça','tomate','carne','farinha']
lista

# Exercício 3 - Crie duas strings e concatene as duas em uma terceira string
s1 = 'carro'
s2 = 'casa'
s3 = s1 + s2
print(s3)

# Exercício 4 - Crie uma tupla com os seguintes elementos: 1, 2, 2, 3, 4, 4, 4, 5 e depois utilize a função count do 
# objeto tupla para verificar quantas vezes o número 4 aparece na tupla
t = (1,2,2,3,4,4,4,5)
t.count(4)

# Exercício 5 - Crie um dicionário vazio e imprima na tela
dic = {}
dic

# Exercício 6 - Crie um dicionário com 3 chaves e 3 valores e imprima na tela
dic = {'carro': 1,'moto':2,'caminhão':3}
dic

# Exercício 7 - Adicione mais um elemento ao dicionário criado no exercício anterior e imprima na tela
dic['barco'] = 4
dic

# Exercício 8 - Crie um dicionário com 3 chaves e 3 valores. Um dos valores deve ser uma lista de 2 elementos numéricos. 
# Imprima o dicionário na tela.

dic={'tv': 10, 'games': 20, 'pc':[4,5]}
dic

# Exercício 9 - Crie uma lista de 4 elementos. O primeiro elemento deve ser uma string, 
# o segundo uma tupla de 2 elementos, o terceiro um dcionário com 2 chaves e 2 valores e 
# o quarto elemento um valor do tipo float.
# Imprima a lista na tela.
lista = ['aviao',(1,2), {'key':123, 'Key2':456}, 7.62]
lista

# Exercício 10 - Considere a string abaixo. Imprima na tela apenas os caracteres da posição 1 a 18.
frase = 'Cientista de Dados é o profissional mais sexy do século XXI'

for i in range(0,18):
    print(frase[i], end='')